### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by blehman** [jeffakolb/Gnip-Trend-Detection#2]
Following the README, the following error occurs. 
<pre>
Gnip-Trend-Detection$ ./rebin.py -i example/scotus.txt -o example/scotus.pkl -c example/config.cfg
Traceback (most recent call last):
  File "./rebin.py", line 237, in <module>
    serializer = importlib.import_module(arg.serializer)
NameError: name 'arg' is not defined
<pre>

**Comment by jeffakolb** [comment]
Thanks. Please pull and test that it's fixed.
