### ISSUE TITLE
Reference trends

### ISSUE THREAD

**Issue by mihai-varga** [jeffakolb/Gnip-Trend-Detection#5]
Hi @jeffakolb . I've read the paper behind this and it seems really cool. I would like to try a trend detection algorithm on Wikipedia for a school project. I was wondering if it would be possible to make the "Reference trends/non-trends" data set public so that I'd have a starting point, as I haven't yet found a reliable way to extract this kind of data from Wikipedia.
Thanks.

**Comment by jeffakolb** [comment]
A decent set of reference time series are in `example/library.pkl`, which is used in the example in the README. But think of this as just a starting point, because the labels and generation details are not public, and all the assumptions I made might not be relevant.

**Comment by mihai-varga** [comment]
I see. I'll start with those then. Thanks :)
