### ISSUE TITLE
error in example

### ISSUE THREAD

**Issue by blehman** [jeffakolb/Gnip-Trend-Detection#6]
Running python==3.4 and managing env w/ anaconda, the installation process was successful. However, this error appears:

```
Gnip-Trend-Detection$ cat example/example.csv | ./trend_rebin.py -c example/config.cfg > example/scotus_rebinned.csv
```

...
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ

**Comment by jeffakolb** [comment]
You probably need to set your [Matplotlib backend](http://matplotlib.org/faq/usage_faq.html#what-is-a-backend) correctly. I added a note in the README.
